# Generated by Django 2.1.4 on 2018-12-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_events',
            fields=[
                ('event_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('event_category', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=20)),
                ('headline', models.CharField(max_length=20)),
                ('host_country', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=20)),
                ('event_score', models.IntegerField()),
                ('scoring_standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Award_information',
            fields=[
                ('award_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('award_code', models.CharField(max_length=20)),
                ('award_name', models.CharField(max_length=20)),
                ('award_grade', models.CharField(max_length=20)),
                ('award_number', models.IntegerField()),
                ('my_ranking', models.CharField(max_length=20)),
                ('awarding_score', models.IntegerField()),
                ('scoring_standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('book_category', models.CharField(max_length=20)),
                ('book_name', models.CharField(max_length=20)),
                ('publisher_name', models.CharField(max_length=20)),
                ('word_count', models.IntegerField()),
                ('number_of_authors', models.IntegerField()),
                ('my_ranking', models.CharField(max_length=20)),
                ('book_score', models.IntegerField()),
                ('word_count_standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('patent_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('patent_category', models.CharField(max_length=20)),
                ('patent_no', models.CharField(max_length=20)),
                ('patent_name', models.CharField(max_length=20)),
                ('patent_number', models.IntegerField()),
                ('my_ranking', models.CharField(max_length=20)),
                ('patent_score', models.IntegerField()),
                ('scoring_standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question_identification',
            fields=[
                ('identification_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('identification_category', models.CharField(max_length=20)),
                ('identification_name', models.CharField(max_length=20)),
                ('identification_unit', models.CharField(max_length=20)),
                ('number_of_completions', models.IntegerField()),
                ('my_ranking', models.CharField(max_length=20)),
                ('identification_time', models.DateField()),
                ('identification_score', models.IntegerField()),
                ('scoring_standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter_information',
            fields=[
                ('reporter_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('reporter_real_name', models.CharField(max_length=20)),
                ('reporter_gender', models.CharField(max_length=2)),
                ('reporter_date_of_birth', models.DateField()),
                ('reporter_identity_number', models.CharField(max_length=18)),
                ('reporter_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Research_projects',
            fields=[
                ('project_number', models.AutoField(primary_key=True, serialize=False)),
                ('project_category', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('contract_no', models.CharField(max_length=20)),
                ('participants_number', models.IntegerField()),
                ('my_ranking', models.CharField(max_length=20)),
                ('project_leader', models.CharField(max_length=20)),
                ('project_funding', models.IntegerField()),
                ('project_score', models.IntegerField()),
                ('funding_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scientific_Papers',
            fields=[
                ('paper_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('paper_category', models.CharField(max_length=20)),
                ('paper_name', models.CharField(max_length=20)),
                ('journal_title', models.CharField(max_length=20)),
                ('journal_number', models.CharField(max_length=20)),
                ('inclusion_factor', models.IntegerField()),
                ('number_of_authors', models.IntegerField()),
                ('my_ranking', models.CharField(max_length=20)),
                ('paper_score', models.IntegerField()),
                ('scoring_standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='System_log',
            fields=[
                ('log_numbering', models.AutoField(primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('log_operator_id', models.ImageField(upload_to='')),
                ('log_content', models.CharField(max_length=100)),
                ('log_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_real_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=18)),
                ('user_permission', models.CharField(max_length=20)),
                ('user_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='scientific_papers',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='research_projects',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='reporter_information',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='question_identification',
            name='identification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='patent',
            name='patent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='award_information',
            name='award_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
        migrations.AddField(
            model_name='academic_events',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User'),
        ),
    ]
