# Generated by Django 2.1.4 on 2018-12-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=18, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permission',
            field=models.CharField(max_length=20, verbose_name='用户权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_real_name',
            field=models.CharField(max_length=20, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_unit',
            field=models.CharField(max_length=20, verbose_name='用户单位'),
        ),
    ]
