# Generated by Django 2.1.4 on 2018-12-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20181221_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_events',
            name='event_category',
            field=models.CharField(max_length=20, verbose_name='活动类别'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='event_name',
            field=models.CharField(max_length=20, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='event_score',
            field=models.IntegerField(verbose_name='活动得分'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='headline',
            field=models.CharField(max_length=20, verbose_name='报告题目'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='host_country',
            field=models.CharField(max_length=20, verbose_name='举办国家'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='organizer',
            field=models.CharField(max_length=20, verbose_name='举办单位'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='scoring_standard',
            field=models.CharField(max_length=20, verbose_name='计分标准'),
        ),
        migrations.AlterField(
            model_name='academic_events',
            name='venue',
            field=models.CharField(max_length=20, verbose_name='举办地点'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='award_code',
            field=models.CharField(max_length=20, verbose_name='获奖代码'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='award_grade',
            field=models.CharField(max_length=20, verbose_name='获奖等级'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='award_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='award_name',
            field=models.CharField(max_length=20, verbose_name='获奖名称'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='award_number',
            field=models.IntegerField(verbose_name='获奖人数'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='awarding_score',
            field=models.IntegerField(verbose_name='获奖得分'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='my_ranking',
            field=models.CharField(max_length=20, verbose_name='本人排名'),
        ),
        migrations.AlterField(
            model_name='award_information',
            name='scoring_standard',
            field=models.CharField(max_length=20, verbose_name='计分标准'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(max_length=20, verbose_name='著作类别'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=20, verbose_name='著作名称'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_score',
            field=models.IntegerField(verbose_name='著作分数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='my_ranking',
            field=models.CharField(max_length=20, verbose_name='本人排名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_authors',
            field=models.IntegerField(verbose_name='作者人数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(max_length=20, verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='book',
            name='word_count',
            field=models.IntegerField(verbose_name='字数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='word_count_standard',
            field=models.CharField(max_length=20, verbose_name='字数分标准'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='my_ranking',
            field=models.CharField(max_length=20, verbose_name='本人排名'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_category',
            field=models.CharField(max_length=20, verbose_name='专利类别'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_name',
            field=models.CharField(max_length=20, verbose_name='专利名称'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_no',
            field=models.CharField(max_length=20, verbose_name='专利号'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_number',
            field=models.IntegerField(verbose_name='持有人数'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_score',
            field=models.IntegerField(verbose_name='专利得分'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='scoring_standard',
            field=models.CharField(max_length=20, verbose_name='计分标准'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='identification_category',
            field=models.CharField(max_length=20, verbose_name='鉴定类别'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='identification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='identification_name',
            field=models.CharField(max_length=20, verbose_name='鉴定名称'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='identification_score',
            field=models.IntegerField(verbose_name='鉴定得分'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='identification_time',
            field=models.DateField(verbose_name='鉴定时间'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='identification_unit',
            field=models.CharField(max_length=20, verbose_name='鉴定单位'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='my_ranking',
            field=models.CharField(max_length=20, verbose_name='本人排名'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='number_of_completions',
            field=models.IntegerField(verbose_name='完成人数'),
        ),
        migrations.AlterField(
            model_name='question_identification',
            name='scoring_standard',
            field=models.CharField(max_length=20, verbose_name='计分标准'),
        ),
        migrations.AlterField(
            model_name='reporter_information',
            name='reporter_date_of_birth',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='reporter_information',
            name='reporter_gender',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='reporter_information',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='reporter_information',
            name='reporter_identity_number',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='reporter_information',
            name='reporter_real_name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='reporter_information',
            name='reporter_unit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='contract_no',
            field=models.CharField(max_length=20, verbose_name='合同号'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='funding_score',
            field=models.IntegerField(verbose_name='经费分值'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='my_ranking',
            field=models.CharField(max_length=20, verbose_name='本人排名'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='participants_number',
            field=models.IntegerField(verbose_name='参加人数'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='project_category',
            field=models.CharField(max_length=20, verbose_name='课题类别'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='project_funding',
            field=models.IntegerField(verbose_name='课题经费'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='project_leader',
            field=models.CharField(max_length=20, verbose_name='课题负责人'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='project_name',
            field=models.CharField(max_length=20, verbose_name='课题名称'),
        ),
        migrations.AlterField(
            model_name='research_projects',
            name='project_score',
            field=models.IntegerField(verbose_name='课题得分'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='inclusion_factor',
            field=models.IntegerField(verbose_name='收录因子'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='journal_number',
            field=models.CharField(max_length=20, verbose_name='期刊编号'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='journal_title',
            field=models.CharField(max_length=20, verbose_name='期刊名称'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='my_ranking',
            field=models.CharField(max_length=20, verbose_name='本人排名'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='number_of_authors',
            field=models.IntegerField(verbose_name='作者人数'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='paper_category',
            field=models.CharField(max_length=20, verbose_name='论文类别'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.User', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='paper_name',
            field=models.CharField(max_length=20, verbose_name='论文名称'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='paper_score',
            field=models.IntegerField(verbose_name='论文分数'),
        ),
        migrations.AlterField(
            model_name='scientific_papers',
            name='scoring_standard',
            field=models.CharField(max_length=20, verbose_name='计分标准'),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='log_content',
            field=models.CharField(max_length=100, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='log_ip',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='log_operator_id',
            field=models.ImageField(upload_to='', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=18, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permission',
            field=models.CharField(max_length=20, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_real_name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_unit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
    ]
