# Generated by Django 2.1.4 on 2018-12-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20181221_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
    ]
