# Generated by Django 2.1.4 on 2018-12-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20181221_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic_events',
            options={'verbose_name_plural': '学术活动'},
        ),
        migrations.AlterModelOptions(
            name='award_information',
            options={'verbose_name_plural': '获奖信息'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '著作'},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'verbose_name_plural': '专利'},
        ),
        migrations.AlterModelOptions(
            name='question_identification',
            options={'verbose_name_plural': '课题鉴定'},
        ),
        migrations.AlterModelOptions(
            name='reporter_information',
            options={'verbose_name_plural': '申报人信息'},
        ),
        migrations.AlterModelOptions(
            name='research_projects',
            options={'verbose_name_plural': '科研课题信息'},
        ),
        migrations.AlterModelOptions(
            name='scientific_papers',
            options={'verbose_name_plural': '科技论文'},
        ),
        migrations.AlterModelOptions(
            name='system_log',
            options={'verbose_name_plural': '系统日志'},
        ),
    ]
